AllCops:
  Exclude:
    - Gemfile
    - Rakefile
    - bin/*
    - spec/**/**
    - fitness_functions/**/**
    - system/**/**
    - db/**/**

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/LineLength:
  Max: 190

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/GlobalVars:
  Enabled: false

Metrics/MethodLength:
  Max: 77

Metrics/BlockLength:
  Max: 177

Naming/PredicateName:
  Enabled: false

Style/GuardClause:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Style/MixinUsage:
  Enabled: false

Lint/AmbiguousOperator:
  Enabled: false

Naming/MemoizedInstanceVariableName:
  Enabled: false

Naming/VariableNumber:
  Enabled: false

Layout/DefEndAlignment:
  Enabled: false

Style/MultilineIfModifier:
  Enabled: false

Style/RaiseArgs:
  Enabled: false

Style/IdenticalConditionalBranches:
  Enabled: false

Style/ExplicitBlockArgument:
  Enabled: false

Style/RedundantFreeze:
  Enabled: false

Style/RedundantInterpolation:
  Enabled: false

Style/NumericLiteralPrefix:
  Enabled: false

Layout/EmptyLineBetweenDefs:
  Enabled: false

Style/HashSyntax:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false